basic.forever(function () {
    for (let Y = 0; Y <= 4; Y++) {
        if (Y == 4) {
            continue;
        }
        for (let X = 0; X <= 4; X++) {
            if (X == 4) {
                led.plot(4, 4)
                basic.pause(200)
                led.plot(4, 3)
                basic.pause(200)
                led.plot(4, 2)
                basic.pause(200)
                led.plot(4, 1)
                basic.pause(200)
                led.plot(4, 0)
                basic.pause(200)
                led.plot(3, 0)
                basic.pause(200)
                led.plot(3, 1)
                basic.pause(200)
                led.plot(3, 2)
                basic.pause(200)
                led.plot(3, 3)
                basic.pause(200)
                led.plot(3, 4)
                basic.pause(200)
                led.plot(2, 4)
                basic.pause(200)
                led.plot(2, 3)
                basic.pause(200)
                led.plot(2, 2)
                basic.pause(200)
                led.plot(2, 1)
                basic.pause(200)
                led.plot(2, 0)
                basic.pause(200)
                led.plot(1, 0)
                basic.pause(200)
                led.plot(1, 1)
                basic.pause(200)
                led.plot(1, 2)
                basic.pause(200)
                led.plot(1, 3)
                basic.pause(200)
                led.plot(1, 4)
                basic.pause(200)
                led.plot(0, 4)
                basic.pause(200)
                led.plot(0, 3)
                basic.pause(200)
                led.plot(0, 2)
                basic.pause(200)
                led.plot(0, 1)
                basic.pause(200)
                led.plot(0, 0)
                basic.pause(200)
            }
        }
    }
})
